export const supervisors = {
    'annajiat@bracu.ac.bd': 'Mr. Annajiat Alim Rasel (AAR)',
    'abid.abrar@bracu.ac.bd': 'Mr. Mohammed Abid Abrar (ABA)',
    'avijit.biswas@bracu.ac.bd': 'Avijit Biswas (ABW)',
    'amitabha@bracu.ac.bd': 'Dr. Amitabha Chakrabarty (ACH)',
    'ankan.ghosh@bracu.ac.bd': 'Ankan Ghosh Dastider (AGD)',
    'ahanaf.hassan@bracu.ac.bd': 'Ms. Ahanaf Hassan Rodoshi (AHR)',
    'abid.jahan@bracu.ac.bd': 'Abid Jahan Apon (AJA)',
    'aminul.huq@bracu.ac.bd': 'Mr. Aminul Huq (AMH)',
    'abu.khan@bracu.ac.bd': 'Dr. Abu Mohammad Khan (AMK)',
    'arif.shakil@bracu.ac.bd': 'Mr. Arif Shakil (ARF)',
    'ashraful.alam@bracu.ac.bd': 'Dr. Md. Ashraful Alam (ASA)',
    'ajmain.ahmed@bracu.ac.bd': 'Ajmain Yasar Ahmed (AYR)',
    'rajib.hasan@bracu.ac.bd': 'Mr. Beig Rajibul Hasan (BRH)',
    'shoaib.ahmed@bracu.ac.bd': 'Shoaib Ahmed Dipu (DPU)',
    'ziaul.karim@bracu.ac.bd': 'Mr. Dewan Ziaul Karim (DZK)',
    'esfar.alam@bracu.ac.bd': 'Mr. A. M. Esfar-E-Alam (ESF)',
    'farhan.feroz@bracu.ac.bd': 'Mr. Farhan Feroz (FFZ)',
    'fakhruddin.gazzali@bracu.ac.bd': 'Md. Fakhruddin Gazzali (FGZ)',
    'faisal.ahmed@bracu.ac.bd': 'Md Faisal Ahmed (FLA)',
    'fairoz.khan@bracu.ac.bd': 'Ms. Fairoz Nower Khan (FNK)',
    'farig.sadeque@bracu.ac.bd': 'Dr. Farig Yousuf Sadeque (FRS)',
    'imran.azad@bracu.ac.bd': 'Mr. Md. Imran Bin Azad (IBA)',
    'rabeeb.ibrat@bracu.ac.bd': 'Rabeeb Ibrat (IBR)',
    'jumana@bracu.ac.bd': 'Ms. Jumana (JMN)',
    'jannatun.noor@bracu.ac.bd': 'Ms. Jannatun Noor Mukta (JNM)',
    'khalilur@bracu.ac.bd': 'Dr. Md. Khalilur Rahman (KHR)',
    'kaykobad@bracu.ac.bd': 'Dr. Mohammad Kaykobad (KKB)',
    'majumdar@bracu.ac.bd': 'Dr. Mahbubul Alam Majumdar [Dean] (MAM)',
    'mehedi.hasan.himel@bracu.ac.bd': 'Mr. Mehedi Hasan Himel (MEH)',
    'rabiul.alam@bracu.ac.bd': 'Dr. Md. Golam Rabiul Alam (MGR)',
    'mursalin.habib@bracu.ac.bd': 'Mr. Mursalin Habib (MHB)',
    'iqbal.hossain@bracu.ac.bd': 'Dr. Muhammad Iqbal Hossain (MIH)',
    'mostakim@bracu.ac.bd': 'Mr. Moin Mostakim (MMM)',
    'meem.arafat@bracu.ac.bd': 'Meem Arafat Manab (MNB)',
    'mobashir.monim@bracu.ac.bd': 'Mr. Mobashir Monim (MOM)',
    'mabdullah@bracu.ac.bd': 'Dr. Matin Saad Abdullah (MSA)',
    'sadek.ferdous@bracu.ac.bd': 'Dr. Md Sadek Ferdous (MSF)',
    'md.saiful.islam@bracu.ac.bd': 'Mr. Md. Saiful Islam (MSI)',
    'sayeed.mohammad@bracu.ac.bd': 'Mir Sayeed Mohammad (MSM)',
    'zadid.hasan@bracu.ac.bd': 'Mr. Mohammad Zahidul Hasan (MZH)',
    'atm.mizanur@bracu.ac.bd': 'A.T.M Mizanur Rahman (MZU)',
    'naziul.haque@bracu.ac.bd': 'Mr. A.K.M. Naziul Haque (NAH)',
    'najeefa.chy@bracu.ac.bd': 'Ms. Najeefa Nikhat Choudhury (NNC)',
    'nadia.rubaiyat@bracu.ac.bd': 'Ms. Nadia Rubaiyat (NRT)',
    'nur.yanhaona@bracu.ac.bd': 'Dr. Muhammad Nur Yanhaona (NYN)',
    'nazia.afreen@bracu.ac.bd': 'Nazia Afreen (NZF)',
    'nabuat.zaman@bracu.ac.bd': 'Mr. Nabuat Zaman Nahim (NZN)',
    'rubayat.ahmed@bracu.ac.bd': 'Mr. Rubayat Ahmed Khan (RAK)',
    'ruhan.islam@bracu.ac.bd': 'Ruhan Islam (RIM)',
    'rahman.rafeed@bracu.ac.bd': 'Mr. Rafeed Rahman (RRH)',
    'rk.saha@bracu.ac.bd': 'Mr. Ramkrishna Saha (RSA)',
    'salman.sayeed@bracu.ac.bd': 'Mr. Salman Sayeed Khan (SAD)',
    'sifat.jahan@bracu.ac.bd': 'Ms. Sifat E Jahan (SEJ)',
    'shahrar.fatemi@bracu.ac.bd': 'Md Shahrar Fatemi (SHF)',
    'shahriar.rahman@bracu.ac.bd': 'Shahriar Rahman Rana (SHR)',
    'shadman.shahriar@bracu.ac.bd': 'Mr. Shadman Shahriar (SHS)',
    'skazi@bracu.ac.bd': 'Dr. Sadia Hamid Kazi [Chairperson] (SKZ)',
    'mirza.mugdho@bracu.ac.bd': 'Mr. Mirza Md. Tanjim Shorif Mugdho (SMU)',
    'ramisa.fariha@bracu.ac.bd': 'Ms. Syeda Ramisa Fariha (SRF)',
    'seraj.mehnaz@bracu.ac.bd': 'Ms. Mehnaz Seraj (SRJ)',
    'mirza.tausif@bracu.ac.bd': 'Mr. Mirza Md. Tausif Shorif Snigdho (SSN)',
    'shoumo.hasan@bracu.ac.bd': 'Mr. Syed Zamil Hasan Shoumo (SZH)',
    'tanvir.ahmed@bracu.ac.bd': 'Mr. Tanvir Ahmed (TAA)',
    'tawhid.anwar@bracu.ac.bd': 'Mr. Md. Tawhid Anwar (TAW)',
    'taufiqul.islam@bracu.ac.bd': 'Taufiqul Islam Khan (TIK)',
    'tamkin.mahmud@bracu.ac.bd': 'Mr. Tamkin Mahmud Tan (TMD)',
    'tanzim.reza@bracu.ac.bd': 'Mr. Md. Tanzim Reza (TRZ)',
    'warida.rashid@bracu.ac.bd': 'Ms. Warida Rashid (WAR)',
    'zahin.ahmed@bracu.ac.bd': 'Zahin Ahmed (ZAD)',
    'zaber.mohammad@bracu.ac.bd': 'Mr. Zaber Mohammad (ZMD)',
    'zahin.wahab@bracu.ac.bd': 'Ms. Zahin Wahab (ZWA)',
    'asif.hossain@bracu.ac.bd': 'Md Asif Hossain Bhuiyan (AHB)',
    'saiful.bari@bracu.ac.bd': 'Md. Saiful Bari Siddiqui (SBS)',
    'tasnim.ferdous@bracu.ac.bd': 'Tasnim Ferdous (TAF)',
    'narzu.tarannum@bracu.ac.bd': 'Narzu Tarannum (NTR)',
    'abdur.rahman@bracu.ac.bd': 'Md. Abdur Rahman (ADR)',
};